// Generated by cbindgen

#ifndef HEARTWOOD_BRIDGE_H
#define HEARTWOOD_BRIDGE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Advertized node features. Signals what services the node supports.
 */
typedef struct Features Features;

/**
 * A valid threshold for the identity [`Doc`].
 *
 * It can only be constructed via [`Threshold::new`] or [`Threshold::MIN`].
 */
typedef struct Threshold Threshold;

/**
 * Timestamp used for COB operations.
 */
typedef struct Timestamp Timestamp;











/**
 * Initialize Radicle authentication (rad auth --alias <name>)
 */
char *rad_auth(const char *alias);

void hw_hello_world(void);

#endif  /* HEARTWOOD_BRIDGE_H */
